### ISSUE TITLE
ERROR: Got unexpected response from the API: Service not enabled

### ISSUE THREAD

**Issue by seevee** [wingrunr21/hassio-xcel-itron-mqtt#1]
## Context

This error occurs when trying to start the add on after completing the steps as listed in the README. Xcel's website shows:

* XCEL ENERGY LAUNCHPAD: `Enrolled`
  * Meter Setup: `Ready to Go`
  * Wi-Fi Connectivity: `Connected to CORRECT_SSID`
* MY DEVICES
  * Home Assistant entry for the LDFI populated by the addon

I suspect this error indicates that the MQTT service itself is not enabled. See logs below for the traceback.

## Logs

<details>
<summary>addon logs:</summary>

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Xcel iTron MQTT
 Bridge from Xcel iTron smart meters to MQTT
-----------------------------------------------------------
 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2023.12.4
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-xcel-itron-mqtt: starting
[15:07:18] INFO: Initializing Xcel iTron2MQTT
s6-rc: info: service init-xcel-itron-mqtt successfully started
s6-rc: info: service xcel-itron-mqtt: starting
s6-rc: info: service xcel-itron-mqtt successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[15:07:21] INFO: Starting Xcel iTron2MQTT
[15:07:22] ERROR: Got unexpected response from the API: Service not enabled
Traceback (most recent call last):
  File "/opt/xcel_itron2mqtt/main.py", line 79, in <module>
    meter = xcelMeter(INTEGRATION_NAME, ip_address, port_num, creds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 57, in __init__
    self.mqtt_client = self.setup_mqtt(self.mqtt_server_address, self.mqtt_port)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xcel_itron2mqtt/xcelMeter.py", line 181, in setup_mqtt
    client.connect(mqtt_server_address, mqtt_port)
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 912, in connect
    self.connect_async(host, port, keepalive,
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 978, in connect_async
    raise ValueError('Invalid host.')
ValueError: Invalid host.
[15:07:36] INFO: Service Xcel iTron2MQTe exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service xcel-itron-mqtt: stopping
s6-rc: info: service xcel-itron-mqtt successfully stopped
s6-rc: info: service init-xcel-itron-mqtt: stopping
s6-rc: info: service init-xcel-itron-mqtt successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
</details>

## Additional Info

* I struggled to get the WiFi connected until I un-hid the SSID
* I did not follow the enrollment steps exactly - I was able to enroll in Launchpad before requesting SDK access (it may be that this step is no longer necessary?)
* I had, previously, successfully set up the Mosquitto broker addon for another purpose, then disabled and deleted prior to the steps taken here

**Comment by wingrunr21** [comment]
Ya, I put a note in the [Future](https://github.com/wingrunr21/hassio-xcel-itron-mqtt#future) section in the README about allowing external brokers. Need to make that enhancement. It would need new config options and a modification of [this](https://github.com/wingrunr21/hassio-xcel-itron-mqtt/blob/main/xcel-itron-mqtt/rootfs/etc/s6-overlay/s6-rc.d/xcel-itron-mqtt/run#L9-L13) to use them (while keeping the ability to use the HASS managed broker if unset).

**Comment by seevee** [comment]
I did read the README and I understand I can't run this with an external broker, these logs are when attempting to run it with the bundled broker.

Any idea why I'd be getting this error message?

**Comment by wingrunr21** [comment]
Hmm, I'm not sure. It's just using the [bashio Services API](https://developers.home-assistant.io/docs/add-ons/communication#services-api) to query the [MQTT service](https://developers.home-assistant.io/docs/api/supervisor/endpoints#service). If you curl that endpoint does it give you a valid response? Wonder if something is funky with the install/uninstall thing. I'd think it would _just work_ given you're on HassOS

**Comment by seevee** [comment]
Huh yeah that's strange, I get a valid response from `/api/services/` but not from `/api/services/mqtt`.

I'll try fiddling around with the MQTT integration and report back.

**Comment by seevee** [comment]
Okay, so I've reinstalled the Mosquitto broker add-on and reconfigured the MQTT integration. After all that, `GET` `/api/services/mqtt` still gives me a 404, but I can successfully publish via `POST` to `/api/services/mqtt/publish`:

```
❯ curl \
-H "Authorization: Bearer TOKEN" \
-H "Content-Type: application/json" \
http://homeassistant-ip:8123/api/services/mqtt
404: Not Found
```
```
❯ curl -X POST \
-H "Authorization: Bearer TOKEN" \
-H "Content-Type: application/json" \
-d '{"payload": "Curl Test", "topic": "home/notification"}' \
http://homeassistant-ip:8123/api/services/mqtt/publish
[]
```

![image](https://github.com/wingrunr21/hassio-xcel-itron-mqtt/assets/4810018/06f3dbf7-edd5-441b-9061-f0ffcf518ba0)

I don't have a clue why this would be the case, but I think it's pretty clearly an issue with either my configuration or HassOS, not this project.

**Comment by seevee** [comment]
Just to close the loop here, MQTT discovery started working for me, but only after updating to HA 2024.1.

As for why that worked? 🤷

**Comment by wdehoogh1** [comment]
I was running into the same issue and it appears the problem was with my MQTT configuration as well. I had been running EMQX and service was not found. I switched to Mosquitto and everything suddenly worked. MQTT is a total black box for me so I must have had something configured incorrectly in EMQX I guess?

**Comment by wingrunr21** [comment]
If you are using the Mosquito add-on, I'm using Home Assistant's service discovery functionality to connect to MQTT. If EMQX doesn't implement that, that'd be why it didn't work and suddenly did. I've got a roadmap item to add support for other MQTT providers (or figure out how to enable HASS's service discovery to do that if they are already configured).

**Comment by wdehoogh1** [comment]
I have no idea if EMQX does, I was only using that provider because that's what I used before in docker before I switched everything to HAOS. I don't really know how to configure a MQTT provider aside from the very basic level. I just point everything at it and hope it works.
