### ISSUE TITLE
Addon Failing to install in HAOS 12.3/Core 2024.5.5

### ISSUE THREAD

**Issue by take-a-CHANCE** [wingrunr21/hassio-xcel-itron-mqtt#14]
Trying to add the add-on and I get the error: 
`Failed to to call /addons/513749ae_xcel-itron-mqtt/install - The command '/bin/bash -o pipefail -c curl -L https://github.com/zaknye/xcel_itron2mqtt/archive/${XCEL_ITRON2MQTT_SHA}.zip -o /tmp/main.zip &&   cd /tmp && unzip /tmp/main.zip &&   mv /tmp/xcel_itron2mqtt-${XCEL_ITRON2MQTT_SHA}/xcel_itron2mqtt /opt &&   rm /opt/xcel_itron2mqtt/run.sh &&   rm -rf /tmp/main.zip &&   apk del libssl3 libcrypto3 && apk add --no-cache openssl &&   pip3 install --no-cache-dir   --prefer-binary   -r /opt/xcel_itron2mqtt/requirements.txt' returned a non-zero code: 6`

Home Assistant OS 12.3
Home Assistant Core 2024.5.5

from #5 it looks like this required an update to the container but that was a slightly different error code

**Comment by wingrunr21** [comment]
I'll have to dig into this more. I'm not seeing issues building on a few tests and I'm running the same versions.

**Comment by take-a-CHANCE** [comment]
Just checked my supervisor logs by running `ha supervisor logs` in the terminal and I saw "could not resolve github.com" in the install logs for the addon. Changed my DNS settings then ran `ha resolution healthcheck` and that fixed the issue.
