### ISSUE TITLE
Summation Delivered Value stopped

### ISSUE THREAD

**Issue by weedy171** [wingrunr21/hassio-xcel-itron-mqtt#18]
Not sure where the issue could be, i noticed that in my energy graph that it stopped recording any new power being delivered.  The addon was working great. I am not sure if the latest Home assistant updates broke because I was not paying attention to the graph missing like that. I can see the power meter on the network. The logs look clean. Not sure where to look next. Thanks for the help in advance.

 Add-on: Xcel iTron MQTT
 Bridge from Xcel iTron smart meters to MQTT
-----------------------------------------------------------
 Add-on version: 1.2.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / qemux86-64)
 Home Assistant Core: 2024.9.3
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-xcel-itron-mqtt: starting
[08:09:58] INFO: Initializing Xcel iTron2MQTT
s6-rc: info: service init-xcel-itron-mqtt successfully started
s6-rc: info: service xcel-itron-mqtt: starting
s6-rc: info: service xcel-itron-mqtt successfully started
s6-rc: info: service legacy-services: starting
[08:09:58] INFO: Starting Xcel iTron2MQTT
s6-rc: info: service legacy-services successfully started
INFO: Connected to MQTT Broker!

![image](https://github.com/user-attachments/assets/57f1ee05-0add-418a-902b-10620214d66c)

**Comment by wingrunr21** [comment]
Hi,

That's weird. Are you able to see the MQTT messages coming in? (you could connect to your broker with something like [MQTTX](https://mqttx.app) and see). Also, are you located in CO? Xcel seems to be running different firmware in different geographies and I'm wondering if there's something there.

**Comment by dxmnkd316** [comment]
One possible solution. 

I had something similar happen.  You can check if this is the same issue by downloading the Xcel Energy app for the smart meter.  Go through the troubleshooting steps on the app (I can't remember the exact steps, but it's in the help section.  I think I had to go through the process three times, which apparently is some magic number for the meter that resets things.)

Anyways, if you do that and it's still stuck at the same reading, I would contact Xcel Launchpad and have them reboot the agent on the meter.  

But try to rule out communication and MQTT errors before contacting them.  
EnergyLaunchpad@xcelenergy.com

See my comments here:
https://community.home-assistant.io/t/xcel-energy-itron-gen-5-riva/346943/319
https://community.home-assistant.io/t/xcel-energy-itron-gen-5-riva/346943/323

**Comment by weedy171** [comment]
I have the app and it appears the data on there is updating correctly their. I live in WI, I haven’t had had a chance to figure out the MQTT messages.

**Comment by lylydang** [comment]
OP did you find a solution, I just got the same issue for the last few days with Received data, the Delivered data still gets updated and meter stay connected to Wifi.

**Comment by weedy171** [comment]
I did not figure it out.  Tried yesterdays update still same issue.

**Comment by lylydang** [comment]
@weedy171 : I actually emailed them today at EnergyLaunchpad@xcelenergy.com asking them to reboot my meter due to this issue. They haven’t replied but around 20 minutes later all my received/delivered data got updated.

**Comment by wingrunr21** [comment]
Added some docs related to the meter restart

**Comment by weedy171** [comment]
> @weedy171 : I actually emailed them today at [EnergyLaunchpad@xcelenergy.com](mailto:EnergyLaunchpad@xcelenergy.com) asking them to reboot my meter due to this issue. They haven’t replied but around 20 minutes later all my received/delivered data got updated.

Thanks @lylydang -- I had them reboot mine as well and it solved it. Like you said it took a little bit but the data is coming in now. It was weird because on my router it would see it but times you would look on their page and it would say it was not connected, but then at other times it would say it was connected.
