### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by itwasdolly** [wingrunr21/hassio-xcel-itron-mqtt#5]
Hello,

I receive the following error when trying to install the add-on. Any suggestions how to fix?

`The command '/bin/bash -o pipefail -c curl -L https://codeload.github.com/zaknye/xcel_itron2mqtt/zip/refs/heads/main -o /tmp/main.zip && unzip /tmp/main.zip -d /tmp && mv /tmp/xcel_itron2mqtt-main/xcel_itron2mqtt /opt && rm /opt/xcel_itron2mqtt/run.sh && sed -i 's/pyyaml==6.0/pyyaml==6.0.1/g' /opt/xcel_itron2mqtt/requirements.txt && rm -rf /tmp/xcel_itron2mqtt-main/ /tmp/main.zip && pip3 install --no-cache-dir --prefer-binary -r /opt/xcel_itron2mqtt/requirements.txt && apk add --no-cache openssl' returned a non-zero code: 11`

Thanks!

**Comment by loafy28** [comment]
just got the same exact error while trying to install

**Comment by wingrunr21** [comment]
Looks like something with a few pip packages while building the add-on. I'll have to dig in to troubleshoot. Might be just a version mismatch.

You can build locally (if you have docker installed) by cloning the repo, `cd` into the `xcel-itron-mqtt` directory, and run:

`docker build --build-arg BUILD_FROM="ghcr.io/hassio-addons/base-python:12.0.2" -t local/hassio-xcel-itron-mqtt .`

**Comment by itwasdolly** [comment]
Thanks. HAOS install here. I'll have to wait.

**Comment by loafy28** [comment]
I attempted the docker build as suggested above on a test system but got the same message and the end of the build.
[docker build --build-arg BUILD_FROM.txt](https://github.com/wingrunr21/hassio-xcel-itron-mqtt/files/13910251/docker.build.--build-arg.BUILD_FROM.txt)


The command '/bin/bash -o pipefail -c curl -L https://codeload.github.com/zaknye/xcel_itron2mqtt/zip/refs/heads/main -o /tmp/main.zip &&     unzip /tmp/main.zip -d /tmp &&     mv /tmp/xcel_itron2mqtt-main/xcel_itron2mqtt /opt &&     rm /opt/xcel_itron2mqtt/run.sh &&     sed -i 's/pyyaml==6.0/pyyaml==6.0.1/g' /opt/xcel_itron2mqtt/requirements.txt &&     rm -rf /tmp/xcel_itron2mqtt-main/ /tmp/main.zip &&     pip3 install --no-cache-dir       --prefer-binary       -r /opt/xcel_itron2mqtt/requirements.txt &&     apk add --no-cache openssl' returned a non-zero code: 11

**Comment by wingrunr21** [comment]
The error message is further up in your output. You can see it says `ERROR: unable to select packages`.

This appears to be a library conflict in Alpine. I just pushed a few commits + bumped the version which should address it. Built correctly on my HAOS install.

**Comment by itwasdolly** [comment]
Thanks so much! That fixed it. I'm going through the rest of the configuration now.

**Comment by loafy28** [comment]
that did it! - thanks!
