### ISSUE TITLE
SDK Access Unnecessary? 

### ISSUE THREAD

**Issue by ianmtaylor1** [wingrunr21/hassio-xcel-itron-mqtt#7]
Hello,

I was able to set up this add-on without following step 1 (requesting SDK access) in the readme. I suspected it may not be necessary, so I tried to move forward without it and the setup ended up working. Is this step necessary, or should it be removed from the instructions?

Thank you very much for your work!

**Comment by wingrunr21** [comment]
Seems it isn't 😄 . I think it used to be to enroll your meter but appears like it is not anymore.

The SDK is a good resource for troubleshooting as it's the most documentation about how these things talk that's out there (barring the IEEE spec itself)
