### ISSUE TITLE
Updating from zaknye repo?

### ISSUE THREAD

**Issue by dxmnkd316** [wingrunr21/hassio-xcel-itron-mqtt#8]
Are you planning on updating the add-on with the latest changes from zaknye's repo?  Looks like there's been some changes that need to be pulled in so that it will work in certain situations:

See:  https://github.com/zaknye/xcel_itron2mqtt/pull/25

**Comment by wingrunr21** [comment]
Sure, I will update when either I see some folks have tested this (which includes #9) so that it doesn't regress or break for non-Wisconsin folks or I have some time to do it myself.

**Comment by dxmnkd316** [comment]
Sounds good.  Appreciate the work on this add-on and the reply.  If there's anything I can do to help test, I'm more than willing to.  

This was just rolled out into my area of the Twin Cities so I'm willing to help where I can.

**Comment by wingrunr21** [comment]
Ya, I tested it and have been running it. Glad it works for you too.

Some of those unavailable are inaccurate anyway. Xcel only reports unix epoch for the `timePeriodDuration` ones so mine both say 55 years.

**Comment by thor0215** [comment]
The issue with duration was fixed a few days ago
https://github.com/zaknye/xcel_itron2mqtt/pull/29

**Comment by wingrunr21** [comment]
Cool, I'll bump it again then
